
services:
  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001

    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    
    environment:
      POSTGRES_DB: "uploader"
      POSTGRES_USER: "skye"

    ports:
      - 5432:5432